spring:
  data:
    mongodb:
      uri: mongodb+srv://intern_kdy:kBhluHyTkY39Am5m@tm-dev.iv9nb.mongodb.net/posable
#      username: intern_kdy
#      password: kBhluHyTkY39Am5m
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tm-new.c5itfod3ti8q.ap-northeast-2.rds.amazonaws.com/tm-b2c
    username: intern_kdy
    password: xpap.1211
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

